### ISSUE TITLE
フォルダ名にスペースがあるとビルドできない

### ISSUE THREAD

**Issue by Martensiter** [sprphys/Springhead#1]
C:/Users/(*username) のusernameにスペースが入っている場合(ex. Ichii Taro)、pythonがパスを参照できずライブラリのビルドが通りません。

**Comment by sprphys** [comment]
Windowsでの対処を施しました。unixはまだです。

**Comment by sprphys** [comment]
間違えてcloseしてしまったので、もう一度書きます。
Windowsでの対処を施しました。unixはまだです。

**Comment by sprphys** [comment]
兼堀です
unixでの対処も施しました。
確認をお願いします。
